repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.6.3
    hooks:
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix]
      - id: ruff-format

  - repo: https://github.com/codespell-project/codespell
    rev: v2.3.0
    hooks:
      - id: codespell
        files: "src/.*.py"
        args:
          - -L
          - HASS,hass,Hass,ist
          - --skip
          - "package-lock.json,*.map,www/docs/.vitepress/cache/*"

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.11.2
    hooks:
      # - id: mypy
      #   files: "^(sunsynk|hass-addon-multi)/"
      #   additional_dependencies:
      #     ["types-attrs", "attrs>21", "types-PyYAML", "pymodbus"]
      - id: mypy
        files: "sma-em/.*.py"
        additional_dependencies: ["attrs>24", "types-PyYAML"]
      - id: mypy
        files: "sma-em-dev/.*.py"
        additional_dependencies: ["attrs>24", "types-PyYAML"]

  - repo: local
    hooks:
      - id: pylint
        name: pylint
        entry: pylint
        language: system
        types: [python]
        pass_filenames: false
        args: [
            "src",
            "-rn", # Only display messages
            "-sn", # Don't display the score
          ]
