name: SMA Energy Meter
description: Add-on for the SMA Energy meter
version: "5b45e67"
slug: sma-em
image: ghcr.io/kellerza/hass-addon-sma-em
url: "https://github.com/kellerza/hassio-sma-em"
services: ["mqtt:need"]
hassio_api: true
init: false
host_network: true
arch:
    - aarch64
    - amd64
    - armhf
    - armv7
    - i386
options:
    SMA_DEVICES:
        - SERIAL_NR: "007"
          HA_PREFIX: "SMA"
    FIELDS:
        - p1consume
        - "p1consumecounter:max"
        - u1
    THRESHOLD: 80
schema:
    SMA_DEVICES:
        - SERIAL_NR: str
          HA_PREFIX: str
    FIELDS:
        - str
    MCASTGRP: str?
    IPBIND: str?
    THRESHOLD: "int(10,1000)?"
    RECONNECT_INTERVAL: "int(60,86400)?"
    DEBUG: int?
    MQTT_HOST: str?
    MQTT_PORT: port?
    MQTT_USERNAME: str?
    MQTT_PASSWORD: password?
