name: SMA Energy Meter
slug: sma-em
description: Add-on for the SMA Energy meter
version: 2021.9.2
startup: services
boot: auto
url: 'https://github.com/kellerza/hassio-sma-em'
arch:
    - aarch64
    - amd64
    - armhf
    - armv7
    - i386
ports: {}
ports_description: {}
host_network: true
options:
    MQTT_HOST: core-mosquitto
    MQTT_PORT: 1883
    MQTT_USERNAME: hass
    MQTT_PASSWORD: my_very_secure_password
    IPBIND: ""
    SMA_SERIALS: []
    FIELDS:
        - pconsume
        - 'pconsumecounter:max'
        - u1
    THRESHOLD: 80
    RECONNECT_INTERVAL: 86400
    DEBUG: 0
    AUTODISCOVER_CONFIG: []
schema:
    MQTT_HOST: str
    MQTT_PORT: port
    MQTT_USERNAME: str
    MQTT_PASSWORD: password
    IPBIND: str
    SMA_SERIALS:
        - str
    FIELDS:
        - str
    THRESHOLD: 'int(10,1000)'
    RECONNECT_INTERVAL: 'int(60,86400)'
    DEBUG: bool
    AUTODISCOVER_CONFIG:
        -
            key: str
            value: str
