name: Deploy sma-em addon to ghcr.io

on:
  release:
    types:
      - published
  workflow_run:
    workflows: ["CI"]
    branches: [main]
    types:
      - completed
  workflow_dispatch: {}

jobs:
  deployer:
    uses: kellerza/hass-addons/.github/workflows/deployer.yml@main
    secrets: inherit
    with:
      addon-slug: sma-em
      addon-slug-edge: sma-em-dev
      pkg-name: sma
      registry-image: ghcr.io/${{ github.repository_owner }}/hass-addon-sma-em
