name: CI

on: [push, pull_request]

env:
  DEFAULT_PYTHON: 3.12

jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: chartboost/ruff-action@v1
        with:
          version: 0.6.3
      - uses: chartboost/ruff-action@v1
        with:
          version: 0.6.3
          args: "format --check"

  lint:
    name: Check pylint
    needs: [ruff]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ env.DEFAULT_PYTHON }}
      - name: Install Requirements
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements_test.txt
      - name: Run Pylint
        run: pylint src

  mypy:
    name: Check mypy
    needs: [ruff]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ env.DEFAULT_PYTHON }}
      - name: Install Requirements
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements_test.txt
      - name: Run mypy
        run: mypy sma-em/
      - name: Run mypy
        run: mypy sma-em-dev/
